title: OG Nimbi
description: Open-Source Development and Customization
theme: just-the-docs

url: https://darkwater409.github.io/Website

pages:
- index.md
- docs.md
- projects.md
- links.md
- 404.md
- docs/themes.md
- docs/rainmeter.md
- docs/mods.md
- projects/themes/studio-ghibli.md
- projects/themes/hentai-senpai.md
- projects/rainmeter/hentai-senpai.md
- projects/mods/ffxiv/dt-lustful-eyes.md
